require('dotenv').config();

console.log("Access token passed through =", process.env.ACCESS_TOKEN_SECRET);


const express = require('express');
const mysql = require("mysql2");
const path = require("path");
const csv = require("csv-parser");
const multer = require("multer");
const fs = require("fs");
const cors = require('cors');
const jwt = require('jsonwebtoken');
const gemini = require('./gemini');
const bcrypt = require("bcrypt");


const PORT = process.env.PORT || 8080;
//This is the port Mysql operates on.

const app = express();
app.use(express.json());
app.use(cors());

//Connecting to database
const pool = mysql.createPool({

    host: 'localhost',
    user: 'root',  
    database: 'CashGrow',
    password: 'mysqlpass123',
    waitForConnections: true,
    connectTimeout: 10000
    
});

//The csv uploaded by user is saved locally as a temporary file
const upload = multer({ dest: "Uploads/"});
app.post("/csvupload", upload.single("csv"), (req, res) => {

    const results = [];
    const filePath = req.file.path;

    //following code reads the csv file and inputs it into database
    fs.createReadStream(filePath)
    .pipe(csv())
    .on("error", (err) => {
        console.error("CSV Read Error: ", err);
    })
    .on('data', (data) => results.push(data))
    .on('end', () => {

        const headers  = Object.keys(results[0]);
        
        const insertQuery = `INSERT INTO Financials VALUES ?;`;

        const values =  results.map(row => headers.map(headers => row[headers])); //This turns the results into an array of arrays. 

        pool.query(insertQuery, [values], (err, result) => { //Values are inputted  
            fs.unlinkSync(filePath); // Remove temporary file
            if (err) {
              console.error(err);
              return res.status(500).json({ message: 'Database error' });
            }
          });     
  })

  res.json({message: "CSV uploaded successfully"});

})


//image uploaded by user is saved locally as a temporary file
const tree = multer({dest: "Uploads/"});

app.post("/imagecreation", tree.single("image"), async (req, res) => {
    const filepath = req.file.path
    
    try{
        const imageBuffer = await gemini.main(filepath); //Image is generated by the Gemini AI and saved here if successfull

        res.setHeader("Content-Type", "image/png"); //Type of image is specified in the header
        res.send(imageBuffer); 

    }catch(error){

        console.error("Gemini generation failed", error);

        res.status(500).json("failed to generate the image");

    }finally{
        fs.unlinkSync(filepath); //cleans up the temporary image
    }
})

//endpoint handles user's manul input of a transaction
app.post("/transactionsubmit", (req, res) => {
    const { recipient, inout, amount, location, account, date, category } = Object.values(req.body); //each variable represents a value the user inputs
    
    const sql = `INSERT INTO Financials VALUES (?, ?, ?, ?, ?, ?, ?)`;

    const values = [recipient, inout, amount, location, account, date, category]

    pool.query(sql, values, (err) => {
        if(err){
            console.error("Transaction input error:", err);
        }
        res.json("successfull");
        console.log("Successfully inputted data");
        
    })
})

//handles login
app.post("/login", (req,res) => {

    //password is encrypted, the text passed in will not match the one priveded by user
    //Only the username is checked for the time being
    const sql = "SELECT * FROM User WHERE Username = ?"; 
    const pwd = req.body.pwd;
    const values = [
        req.body.user
    ]

    pool.query(sql, values, async (err, data) =>  { //query checks the existence of the user
        if (data.length === 0) {
            return res.status(401).json({ error: "Invalid username" }); 
        }
        if(err){
                console.error("Login failed: ",  err);
        }

        const validatePass = await bcrypt.compare(pwd, data[0].Password); //Uses bcrypt to check the password mathed the encrypted one

        if (!validatePass){
            return res.status(401).json({nessage: "Incorrect password"});
        }

        const user = {idUser: data[0].idUser, username: data[0].Username}; //retuned context to be added to auth
        const accessToken = jwt.sign(user, process.env.ACCESS_TOKEN_SECRET); //gives the user a unique web token
        res.json({accessToken, user});
        
    }
    )
})

//Inserts new user data into the database, encrypts password
app.post('/signup', async (req, res) => {

    const usersql = "INSERT INTO User(Username, Password) VALUES (?, ?)";
    const budgetsql = "INSERT INTO Budgeting(idUser, Budget) VALUES (?, ?)";
    //Two queries are needed as two different table need to be updated
    const { username, password, budget } = req.body;

    try {
        const hashed = await bcrypt.hash(password, 10); //The passed in password is encrypted
        const userValues = [username, hashed];

        pool.query(usersql, userValues, (err, result) => {
            if (err) {
                if (err.code === 'ER_DUP_ENTRY') { //Ensures the username does not already exist
                    return res.status(409).json({ message: "Username already exists" });
                }
                console.error("User insert error:", err);
                return res.status(500).json({ message: "User insert failed" });
            }

            const newId = result.insertId; // The idUser is assigned to the user by the database and is required to update the budget table
                                           // This is returned to be used in the next query

            const budgetValues = [newId, budget];
            //Inserts data into budget table
            pool.query(budgetsql, budgetValues, (budgetErr, budgetResult) => {
                if (budgetErr) {
                    console.error("Budget insert error:", budgetErr);
                    return res.status(500).json({ message: "Budget insert failed" });
                }

                return res.status(201).json({ message: "User and budget created successfully" });
            });
        });

    } catch (err) {
        console.error("Hashing error:", err);
        return res.status(500).json({ message: "Server error during hashing" });
    }
});

//Returns user data
app.get('/userdata', authenticateToken, (req, res) => { //authenticateToken, authenticates the user has the token nrequired to make a query

    const userId = req.user.idUser;

    //Two queries are used to get both the budget gooal and the transaction infromation
    const financesql = "SELECT * FROM Financials WHERE idUser = ?";
    const budgetsql = "SELECT * FROM Budgeting WHERE idUser = ?"

    //The user's ID is used to find the right data to return
    pool.query(financesql, [userId], (err, financeData) => {
        if(err){
            console.error("There was an error fetching the finances");
            return res.status(500).json({error: "Database error"});
        }
    pool.query(budgetsql, [userId], (err, budgetData) => {
        if(err){
            console.error("There was an error fetching the budget: ", err);
            return res.status(500).json({error: "Budgate table, Database error"});
            console.log(budgetData);
        }
        return res.json({finances: financeData, budget: budgetData});
    })
    })
    }
)       

//Authenticates the users token to confirm they can access the data 
function authenticateToken(req, res, next){
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];

    console.log("This is the token: ", token);

    if (token == null) return res.sendStatus(401);

    
    jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, (err, user) => { //automatically checks wether the token supplied is the correct one
        if(err) return res.sendStatus(403);
        req.user = user
        next()
    })
}


app.listen(PORT, () => {
    console.log("Server Listening on PORT:", PORT);
  });